# Generated by Django 5.1.1 on 2025-05-05 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po6', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Техпередел',
                'verbose_name_plural': 'Техпеределы',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='patronymic_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='profile',
            name='redistribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='po6.redistribution'),
        ),
    ]
