# Generated by Django 5.1.1 on 2025-05-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po6', '0002_redistribution_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='addr',
            field=models.CharField(default='0.0.0.0', max_length=64, verbose_name='Адрес'),
        ),
    ]
